import Head from 'next/head';
import Image from 'next/image';
import { Fragment, useEffect, useState, useContext } from 'react';

import Banner from '../components/Banner';
import Card from '../components/card';

import { fetchCoffeeStores } from '../lib/coffee-stores';
import useTrackLocation from '../hooks/use-track-location';
import { ACTION_TYPES, StoreContext } from '../store/store-context';

import styles from '../styles/Home.module.css';

export async function getStaticProps(context) {
	const coffeeStores = await fetchCoffeeStores();

	return {
		props: {
			coffeeStores: coffeeStores,
		}
	}
}

export default function Home(props) {
	// const [coffeeShops, setCoffeeShops] = useState([]);
	const [coffeeStoresError, setCoffeeStoresError] = useState(null);

	const { locationErrorMsg, handleTrackLocation, isFindingLocation } = useTrackLocation();

	const { dispatch, state } = useContext(StoreContext);

	const { coffeeStores, latLong } = state;

	const handleOnBannerBtnClick = () => {
		handleTrackLocation();
	}

	useEffect(() => {
		const setCoffeeStoresByLocation = async () => {
			if (latLong) {
				try {
					console.log(latLong)
					const response = await fetch(
						`/api/getCoffeeStoresByLocation?latLong=${latLong}&limit=20`
					  );
			
					  const coffeeStores = await response.json();
					dispatch({
						type: ACTION_TYPES.SET_COFFEE_STORES,
						payload: { coffeeStores }
					})
					//set coffee stores
				} catch (error) {
					//set error
					setCoffeeStoresError(error.message);
					console.log({ error });
				}
			}
		}
		setCoffeeStoresByLocation();
	}, [latLong, dispatch]);

	return (
		<div className={styles.container}>
		<Head>
			<title>Coffee Connoisseur</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main className={styles.main}>
			<Banner
				buttonText={isFindingLocation ? "Locating..." : "View stores nearby"}
				handleOnClick={handleOnBannerBtnClick}
			/>
			{locationErrorMsg && <p>Something went wrong: {locationErrorMsg}</p>}
			{coffeeStoresError && <p>Something went wrong: {coffeeStoresError}</p>}
			<div className={styles.heroImage}>
				<Image src='/static/hero-image.png' width={700} height={400} alt='banner image'/>
			</div>
			{coffeeStores.length > 0 &&
				<div className={styles.sectionWrapper}>
					<Fragment>
						<h2 className={styles.heading2}>Stores near me</h2>
						<div className={styles.cardLayout}>
							{coffeeStores.map((coffeeStore) => (
								<Card
									key={coffeeStore.id}
									name={coffeeStore.name}
									imgUrl={coffeeStore.imgUrl}
									href={`coffee-store/${coffeeStore.id}`}
									className={styles.card}
								/>
							))}

						</div>
					</Fragment>
				</div>
			}
			{props.coffeeStores.length > 0 &&
				<div className={styles.sectionWrapper}>
					<Fragment>
						<h2 className={styles.heading2}>Toronto stores</h2>
						<div className={styles.cardLayout}>
							{props.coffeeStores.map((coffeeStore) => (
								<Card
									key={coffeeStore.id}
									name={coffeeStore.name}
									imgUrl={coffeeStore.imgUrl}
									href={`coffee-store/${coffeeStore.id}`}
									className={styles.card}
								/>
							))}

						</div>
					</Fragment>
				</div>
			}
		</main>
		</div>
	)
}
